import Header from '@/components/Header';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'SMART',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="font-bodyFont w-full bg-main-bg text-darkText">
                <Header />
                {children}
            </body>
        </html>
    );
}
